apiVersion: v1
kind: Service
metadata:
  name: sample-app-svc
  labels:
    app: sample-app
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - port: 80              # External port (publicly exposed)
      targetPort: 3000      # Port your container listens on
      protocol: TCP
